name: 50mp
favicon: null
layout_spectrum: 0.91618
typography_spectrum: 0.2842
title: Новости фотографии и вдохновения
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0b0c'
    - '#2c2e5e'
    - '#6a5c97'
    - '#f9c795'
    - '#e1772b'
  brandStrength: 0.9671198860742152
  lightness: 0.2805462491232902
  saturation: 0.2731201311107725
  rhythmicContrast: 0.3778690970502794
purpose: []
